version: 2

jobs:
    deploy:
        working_directory: ~/repo
        docker:
            - image: circleci/node:12.8.0
        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Authenticate with registry
                  command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
            - run:
                  name: Publish package
                  command: npm publish

workflows:
    version: 2
    workflow:
        jobs:
            - deploy:
                  filters:
                      branches:
                          ignore: /.*/
                      tags:
                          only: /^v.*/
